[package]
name = "net-loginer"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 3
panic = "abort"
codegen-units = 1

[dependencies]
dotenv = "0.15.0"
get_if_addrs = "0.5.3"
log = "0.4.21"
once_cell = "1.19.0"
serde_json = "1.0.116"

[dependencies.tokio]
version = "1.37.0"
features = ["macros", "rt-multi-thread"]

[dependencies.reqwest]
version = "0.12.4"
features = ["json"]

[dependencies.simple_logger]
version = "5.0.0"
features = ["colors", "timestamps"]

[dependencies.ddddocr]
git = "https://github.com/86maid/ddddocr.git"
branch = "master"
