[package]
name = "net-loginer"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = "z"
strip = true
panic = "abort"
codegen-units = 1

[dependencies]
dotenv = "0.15.0"
get_if_addrs = "0.5.3"
log = "0.4.21"
once_cell = "1.19.0"
serde_json = "1.0.116"
thiserror = "1.0.59"
onnxruntime = "0.0.14"
anyhow = "1.0.83"
url = "2.5.0"
native-tls = "0.2.11"
jpeg-decoder = "0.3.1"

[dependencies.ureq]
version = "2.9.7"
features = ["native-tls"]
default-features = false

[dependencies.image]
version = "0.25.1"
features = ["jpeg"]
default-features = false

[dependencies.simple_logger]
version = "5.0.0"
features = ["colors", "timestamps"]
